import catBuilding from "@/assets/cat-building.jpg";
import catGlass from "@/assets/cat-glass.jpg";
import catAluminium from "@/assets/cat-aluminium.jpg";
import catFinishing from "@/assets/cat-finishing.jpg";
import catTools from "@/assets/cat-tools.jpg";
import catFittings from "@/assets/cat-fittings.jpg";
import catAdhesives from "@/assets/cat-adhesives.jpg";
import catPlumbing from "@/assets/cat-plumbing.jpg";

export const PHONE = "+254 757 773 936";
export const PHONE_HREF = "tel:+254757773936";
export const WHATSAPP = "https://wa.me/254757773936";
export const TIKTOK = "https://www.tiktok.com/@joymax_hardware?_r=1&_t=ZS-98LyWvkKbQI";
export const EMAIL = "captainhardware945@gmail.com";
export const ADDRESS = "Mount kenya building ground floor,Nairobi, Kenya";
export const HOURS = "Mon – Sat: 7:30 AM – 6:00 PM";

export const categories = [
  {
    slug: "building-materials",
    name: "Building Materials",
    blurb: "Cement, steel, aggregates & bulk supplies.",
    image: catBuilding,
  },
  {
    slug: "glass-products",
    name: "Glass Products",
    blurb: "Clear, tinted, tempered & mirror glass.",
    image: catGlass,
  },
  {
    slug: "aluminium",
    name: "Aluminium & Fabrication",
    blurb: "Profiles, frames & custom fabrication.",
    image: catAluminium,
  },
  {
    slug: "finishing",
    name: "Finishing Products",
    blurb: "Paints, primers & surface finishes.",
    image: catFinishing,
  },
  {
    slug: "tools",
    name: "Hardware & Tools",
    blurb: "Hand tools, power tools & accessories.",
    image: catTools,
  },
  {
    slug: "fittings",
    name: "Furniture Fittings",
    blurb: "Handles, hinges, knobs & drawer rails.",
    image: catFittings,
  },
  {
    slug: "adhesives",
    name: "Adhesives & Accessories",
    blurb: "Silicone, glues & sealants.",
    image: catAdhesives,
  },
  {
    slug: "plumbing",
    name: "Plumbing & Electrical",
    blurb: "PVC, fittings & electrical essentials.",
    image: catPlumbing,
  },
];

export const products = [
  {
    id: "p1",
    name: "MDF Screws",
    category: "Screws & Fasteners",
    categorySlug: "tools",
    variant: "Box of 500 · 4x40mm",
    price: "KSh 850",
    image: catTools,
  },
  {
    id: "p2",
    name: "Drawer Rails",
    category: "Drawer Hardware",
    categorySlug: "fittings",
    variant: "Ball-bearing · 450mm",
    price: "KSh 620 /pair",
    image: catFittings,
  },
  {
    id: "p3",
    name: "Glass Catches",
    category: "Glass Accessories",
    categorySlug: "glass-products",
    variant: "Chrome · Magnetic",
    price: "KSh 180",
    image: catGlass,
  },
  {
    id: "p4",
    name: "Cabinet Handles",
    category: "Handles & Fittings",
    categorySlug: "fittings",
    variant: "Brushed steel · 128mm",
    price: "KSh 340",
    image: catFittings,
  },
  {
    id: "p5",
    name: "Door Knobs",
    category: "Handles & Fittings",
    categorySlug: "fittings",
    variant: "Polished chrome",
    price: "KSh 260",
    image: catFittings,
  },
  {
    id: "p6",
    name: "Concealed Hinges",
    category: "Handles & Fittings",
    categorySlug: "fittings",
    variant: "Soft-close · 35mm",
    price: "KSh 220 /pc",
    image: catFittings,
  },
  {
    id: "p7",
    name: "Cylinder Lock",
    category: "Locks & Latches",
    categorySlug: "fittings",
    variant: "Brass · 3 keys",
    price: "KSh 1,450",
    image: catFittings,
  },
  {
    id: "p8",
    name: "Gas Lifts",
    category: "Drawer Hardware",
    categorySlug: "fittings",
    variant: "100N · Cabinet",
    price: "KSh 480",
    image: catFittings,
  },
  {
    id: "p9",
    name: "Glass Cutter",
    category: "Tools",
    categorySlug: "tools",
    variant: "Diamond tip · Pro",
    price: "KSh 720",
    image: catTools,
  },
  {
    id: "p10",
    name: "Mirror Clips",
    category: "Glass Accessories",
    categorySlug: "glass-products",
    variant: "Chrome · Set of 4",
    price: "KSh 240",
    image: catGlass,
  },
  {
    id: "p11",
    name: "Combination Pliers",
    category: "Tools",
    categorySlug: "tools",
    variant: "8 inch · Insulated",
    price: "KSh 950",
    image: catTools,
  },
  {
    id: "p12",
    name: "Screwdriver Set",
    category: "Tools",
    categorySlug: "tools",
    variant: "12 pieces",
    price: "KSh 1,650",
    image: catTools,
  },
  {
    id: "p13",
    name: "Steel Scraper",
    category: "Tools",
    categorySlug: "tools",
    variant: "4 inch",
    price: "KSh 220",
    image: catTools,
  },
  {
    id: "p14",
    name: "Measuring Tape",
    category: "Tools",
    categorySlug: "tools",
    variant: "5 metre · Magnetic",
    price: "KSh 380",
    image: catTools,
  },
  {
    id: "p15",
    name: "Ponal Wood Glue",
    category: "Adhesives & Glues",
    categorySlug: "adhesives",
    variant: "500g bottle",
    price: "KSh 620",
    image: catAdhesives,
  },
  {
    id: "p16",
    name: "Contact Adhesive",
    category: "Adhesives & Glues",
    categorySlug: "adhesives",
    variant: "1 litre tin",
    price: "KSh 890",
    image: catAdhesives,
  },
  {
    id: "p17",
    name: "DLG Glue",
    category: "Adhesives & Glues",
    categorySlug: "adhesives",
    variant: "250ml",
    price: "KSh 450",
    image: catAdhesives,
  },
  {
    id: "p18",
    name: "Silicone Sealant",
    category: "Adhesives & Glues",
    categorySlug: "adhesives",
    variant: "Clear · 300ml",
    price: "KSh 450",
    image: catAdhesives,
  },
  {
    id: "p19",
    name: "Silicone Gun",
    category: "Tools",
    categorySlug: "tools",
    variant: "Heavy-duty",
    price: "KSh 550",
    image: catTools,
  },
  {
    id: "p20",
    name: "Turpentine",
    category: "Finishing",
    categorySlug: "finishing",
    variant: "1 litre",
    price: "KSh 380",
    image: catFinishing,
  },
  {
    id: "p21",
    name: "Cement (50kg)",
    category: "Building Materials",
    categorySlug: "building-materials",
    variant: "OPC 42.5N",
    price: "KSh 650",
    image: catBuilding,
  },
  {
    id: "p22",
    name: "6mm Clear Glass",
    category: "Glass Products",
    categorySlug: "glass-products",
    variant: "Per SQM",
    price: "KSh 950",
    image: catGlass,
  },
  {
    id: "p23",
    name: "PVC Pipes (110mm)",
    category: "Plumbing & Electrical",
    categorySlug: "plumbing",
    variant: "6 metre length",
    price: "KSh 850",
    image: catPlumbing,
  },
  {
    id: "p24",
    name: "Aluminium Frame",
    category: "Aluminium",
    categorySlug: "aluminium",
    variant: "Standard profile",
    price: "KSh 1,800 /m",
    image: catAluminium,
  },
];

export const filterCategories = [
  "All Products",
  "Screws & Fasteners",
  "Locks & Latches",
  "Handles & Fittings",
  "Drawer Hardware",
  "Glass Accessories",
  "Tools",
  "Adhesives & Glues",
  "Building Materials",
  "Plumbing & Electrical",
  "Finishing",
];
